name: Build Package
on: [ pull_request ]
jobs:
  build:
    name: "${{ matrix.os }} - ${{ matrix.irods-version }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ 'rockylinux/rockylinux:8' ]
        irods-version: [ 4.3.2 ]
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Prerequisites
        run:  |
              dnf update -y
              dnf install -y \
                epel-release
              dnf install -y \
                libcurl-devel \
                openssl-devel \
                redhat-lsb-core \
                rpm-build
              dnf install -y \
                dnf-plugin-config-manager \
                dnf-plugins-core
      - name: Install iRODS
        run:  |
              rpm --import https://packages.irods.org/irods-signing-key.asc
              dnf config-manager -y --add-repo https://packages.irods.org/renci-irods.yum.repo
              dnf config-manager -y --set-enabled renci-irods
              dnf config-manager -y --set-enabled powertools
              dnf install -y \
                ninja-build
              dnf install -y \
                "irods-devel-${{ matrix.irods-version }}-0.el8" \
                "irods-runtime-${{ matrix.irods-version }}-0.el8"
      - name: Install iRODS Externals
        run:  |
              dnf update -y
              dnf install -y \
                irods-externals-clang13.0.1-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-fmt-libcxx8.1.1-1 \
                irods-externals-json3.10.4-0 \
                irods-externals-jsoncons0.178.0-0 \
                irods-externals-jwt-cpp0.6.99.1-0 \
                irods-externals-nanodbc-libcxx2.13.0-2 \
                irods-externals-spdlog-libcxx1.9.2-2 \
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cmake -GNinja -B build/ -S .
      - name: Build and Package
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              cmake --build build/ -t package
